### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [MarketVision-Ltd/gtm-template-cookiedialog#1]
https://github.com/MarketVision-Ltd/gtm-template-cookiedialog/blob/c3811e2c77cb7d88673139cb20b8cd2ed98ac174/template.tpl#L240C9-L242C10

When reviewing your template, we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This option is required to be set for any asynchronous consent management script load to delay tag execution.

When reviewing your template, we've also noticed that wait_for_update was set to a default less than 500 milliseconds. When specifying this it's a best practice to give some buffer time to attempt to allow for the updateConsent command to be fired. This is very important when loading the consent management script dynamically.

**Comment by benique** [comment]
Thank you very much for pointing this out. I corrected it and set a minimum of 500ms.

**Comment by philpott** [comment]
Once your done remember to update your template to include the latest version on the top of the versions list.

For more details look see our how to [update article](https://developers.google.com/tag-platform/tag-manager/templates/gallery#update_your_template)

**Comment by benique** [comment]
Thanks. It's done.

**Comment by philpott** [comment]
Thanks for the fix and you'll see your template on the gallery shortly!
